# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

DocumentType.create(category: :property, name: "Appraisal")
DocumentType.create(category: :property, name: "Flood Insurance")
DocumentType.create(category: :property, name: "Hazard Insurance")
DocumentType.create(category: :property, name: "Liability Insurance")
DocumentType.create(category: :property, name: "Phase 1")
DocumentType.create(category: :property, name: "Purchase Agreement")
DocumentType.create(category: :property, name: "P&L Statement")
DocumentType.create(category: :property, name: "Rent Roll")
DocumentType.create(category: :property, name: "Lease Agreement")
DocumentType.create(category: :property, name: "Environmental Questionnaire")
DocumentType.create(category: :property, name: "Survey")
DocumentType.create(category: :property, name: "Tenant")
DocumentType.create(category: :property, name: "Zoning")

DocumentType.create(category: :borrower, name: "Asset Statement")
DocumentType.create(category: :borrower, name: "Attorney")
DocumentType.create(category: :borrower, name: "Bankruptcy Papers")
DocumentType.create(category: :borrower, name: "Bank Statement")
DocumentType.create(category: :borrower, name: "Borrowing Authorization")
DocumentType.create(category: :borrower, name: "Business Debt Schedule")
DocumentType.create(category: :borrower, name: "Business Plan")
DocumentType.create(category: :borrower, name: "Confirmation of Good Standing")
DocumentType.create(category: :borrower, name: "Entity Identification Doc")
DocumentType.create(category: :borrower, name: "Fictitious Name Filing")
DocumentType.create(category: :borrower, name: "Financial Statement")
DocumentType.create(category: :borrower, name: "Formation Doc")
DocumentType.create(category: :borrower, name: "Organization Agreement")
DocumentType.create(category: :borrower, name: "Personal Financial Statement")
DocumentType.create(category: :borrower, name: "Resume")
DocumentType.create(category: :borrower, name: "Schedule of REO")
DocumentType.create(category: :borrower, name: "Spousal Consent")
DocumentType.create(category: :borrower, name: "Tax Return")
DocumentType.create(category: :borrower, name: "Voided Check")

DocumentType.create(category: :guarantor, name: "Asset Statement")
DocumentType.create(category: :guarantor, name: "Bankruptcy Papers")
DocumentType.create(category: :guarantor, name: "Bank Statement")
DocumentType.create(category: :guarantor, name: "Borrowing Authorization")
DocumentType.create(category: :guarantor, name: "Confirmation of Good Standing")
DocumentType.create(category: :guarantor, name: "Entity Identification Doc")
DocumentType.create(category: :guarantor, name: "Fictitious Name Filing")
DocumentType.create(category: :guarantor, name: "Financial Statement")
DocumentType.create(category: :guarantor, name: "Formation Doc")
DocumentType.create(category: :guarantor, name: "Organization Agreement")
DocumentType.create(category: :guarantor, name: "Personal Financial Statement")
DocumentType.create(category: :guarantor, name: "Resume")
DocumentType.create(category: :guarantor, name: "Schedule of REO")
DocumentType.create(category: :guarantor, name: "Spousal Consent")
DocumentType.create(category: :guarantor, name: "Tax Return")
DocumentType.create(category: :guarantor, name: "Voided Check")

DocumentType.create(category: :closing, name: "Broker Demand")
DocumentType.create(category: :closing, name: "Closing Protection Letter")
DocumentType.create(category: :closing, name: "Escrow Instruction Letter")
DocumentType.create(category: :closing, name: "Loan Doc")
DocumentType.create(category: :closing, name: "Prelim Title Report")
DocumentType.create(category: :closing, name: "Wire Instructions")

# Admin.create(user: User.new(email: "admin@blackline.com", password: "mortgage123"))

# Checklist.create(loan: Loan.first, checklist_type: :upload, due_date: Time.zone.now + 7.days, information: "hello", status: :pending, document_description: "upload test 3", name: "upload test 3", document_type_id: "450c37b0-64e6-43c7-9b1e-c68859d7b4fb")
# Checklist.create(loan: Loan.first, checklist_type: :upload, due_date: Time.zone.now + 7.days, information: "hello", status: :pending, document_description: "upload test 4", name: "upload test 4", document_type_id: "4af424ec-274f-4499-bfa5-50902ff3e918")
# Checklist.create(loan: Loan.first, checklist_type: :upload, due_date: Time.zone.now + 7.days, information: "hello", status: :pending, document_description: "upload test 5", name: "upload test 5", document_type_id: "5532ee76-e225-41e1-9ebd-398bd9aab890")
# Checklist.create(loan: Loan.first, checklist_type: :upload, due_date: Time.zone.now + 7.days, information: "hello", status: :pending, document_description: "upload test 6", name: "upload test 6", document_type_id: "6f372f02-cf0d-4eb7-81c3-2f9b83648606")
# Checklist.create(loan: Loan.first, checklist_type: :upload, due_date: Time.zone.now + 7.days, information: "hello", status: :pending, document_description: "upload test 7", name: "upload test 7", document_type_id: "7fb5f21f-3f15-4d19-a3b4-784144df03bd")
# Checklist.create(loan: Loan.first, checklist_type: :upload, due_date: Time.zone.now + 7.days, information: "hello", status: :pending, document_description: "upload test 8", name: "upload test 8", document_type_id: "5c6364ba-4bf2-4512-97de-d79fa3f8d4cb")
# Checklist.create(loan: Loan.first, checklist_type: :upload, due_date: Time.zone.now + 7.days, information: "hello", status: :pending, document_description: "upload test 9", name: "upload test 9", document_type_id: "658bd6a0-b066-4ffd-8e57-6c75356ff6d4")
