# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

DocumentType.create(category: :property, name: "Appraisal")
DocumentType.create(category: :property, name: "Flood Insurance")
DocumentType.create(category: :property, name: "Hazard Insurance")
DocumentType.create(category: :property, name: "Liability Insurance")
DocumentType.create(category: :property, name: "Phase 1")
DocumentType.create(category: :property, name: "Purchase Agreement")
DocumentType.create(category: :property, name: "P&L Statement")
DocumentType.create(category: :property, name: "Rent Roll")
DocumentType.create(category: :property, name: "Lease Agreement")
DocumentType.create(category: :property, name: "Environmental Questionnaire")
DocumentType.create(category: :property, name: "Survey")
DocumentType.create(category: :property, name: "Tenant")
DocumentType.create(category: :property, name: "Zoning")

DocumentType.create(category: :borrower, name: "Asset Statement")
DocumentType.create(category: :borrower, name: "Attorney")
DocumentType.create(category: :borrower, name: "Bankruptcy Papers")
DocumentType.create(category: :borrower, name: "Bank Statement")
DocumentType.create(category: :borrower, name: "Borrowing Authorization")
DocumentType.create(category: :borrower, name: "Business Debt Schedule")
DocumentType.create(category: :borrower, name: "Business Plan")
DocumentType.create(category: :borrower, name: "Confirmation of Good Standing")
DocumentType.create(category: :borrower, name: "Entity Identification Doc")
DocumentType.create(category: :borrower, name: "Fictitious Name Filing")
DocumentType.create(category: :borrower, name: "Financial Statement")
DocumentType.create(category: :borrower, name: "Formation Doc")
DocumentType.create(category: :borrower, name: "Organization Agreement")
DocumentType.create(category: :borrower, name: "Personal Financial Statement")
DocumentType.create(category: :borrower, name: "Resume")
DocumentType.create(category: :borrower, name: "Schedule of REO")
DocumentType.create(category: :borrower, name: "Spousal Consent")
DocumentType.create(category: :borrower, name: "Tax Return")
DocumentType.create(category: :borrower, name: "Voided Check")

DocumentType.create(category: :guarantor, name: "Asset Statement")
DocumentType.create(category: :guarantor, name: "Bankruptcy Papers")
DocumentType.create(category: :guarantor, name: "Bank Statement")
DocumentType.create(category: :guarantor, name: "Borrowing Authorization")
DocumentType.create(category: :guarantor, name: "Confirmation of Good Standing")
DocumentType.create(category: :guarantor, name: "Entity Identification Doc")
DocumentType.create(category: :guarantor, name: "Fictitious Name Filing")
DocumentType.create(category: :guarantor, name: "Financial Statement")
DocumentType.create(category: :guarantor, name: "Formation Doc")
DocumentType.create(category: :guarantor, name: "Organization Agreement")
DocumentType.create(category: :guarantor, name: "Personal Financial Statement")
DocumentType.create(category: :guarantor, name: "Resume")
DocumentType.create(category: :guarantor, name: "Schedule of REO")
DocumentType.create(category: :guarantor, name: "Spousal Consent")
DocumentType.create(category: :guarantor, name: "Tax Return")
DocumentType.create(category: :guarantor, name: "Voided Check")

DocumentType.create(category: :closing, name: "Broker Demand")
DocumentType.create(category: :closing, name: "Closing Protection Letter")
DocumentType.create(category: :closing, name: "Escrow Instruction Letter")
DocumentType.create(category: :closing, name: "Loan Doc")
DocumentType.create(category: :closing, name: "Prelim Title Report")
DocumentType.create(category: :closing, name: "Wire Instructions")

